### ISSUE TITLE
Docker image tag format

### ISSUE THREAD

**Issue by imZack** [MOXA-ISD/developer-docs#6]
Currently we use `moxaisd/thingspro-dev-desktop:linux-amd64` as our image name + tag but there is no version for it.

Maybe we could...
1. Use multiarch and get rid of arch in tag
2. Add version number in tag like `linux-amd64-master`, `linux-amd64-1.0`

**Comment by fcwu** [comment]
It built by drone. I had pushed the first tag to v0.1.0, and version updated in tag. Please check https://hub.docker.com/r/moxaisd/thingspro-dev-desktop/tags/. 

multiarch(manifest) is the best solution. I will add it when this repo supports ARM.

**Comment by imZack** [comment]
Awesome, now we could add a `latest` tag (default tag) always pointing to the latest version and update the docs.
